apiVersion: v1
entries:
  defectdojo:
  - apiVersion: v2
    appVersion: 2.13.1
    created: "2022-09-06T18:28:38.328819+02:00"
    dependencies:
    - condition: mysql.enabled
      name: mysql
      repository: '@bitnami'
      version: ~9.1.7
    - condition: postgresql.enabled
      name: postgresql
      repository: '@bitnami'
      version: ~11.6.5
    - alias: postgresqlha
      condition: postgresqlha.enabled
      name: postgresql-ha
      repository: '@bitnami'
      version: ~9.1.5
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: '@bitnami'
      version: ~9.1.4
    - condition: redis.enabled
      name: redis
      repository: '@bitnami'
      version: ~16.12.0
    description: A Helm chart for Kubernetes to install DefectDojo
    digest: 1c8dcff72401e1e2ba17c5c914102c7c1b60e7d38dbaeeb29469c244ec4ce1d3
    icon: https://www.defectdojo.org/img/favicon.ico
    maintainers:
    - email: defectdojo-project@owasp.org
      name: madchap
      url: https://github.com/DefectDojo/django-DefectDojo
    name: defectdojo
    urls:
    - defectdojo-1.6.37.tgz
    version: 1.6.37
generated: "2022-09-06T18:28:38.309721+02:00"
