apiVersion: v1
entries:
  defectdojo:
  - apiVersion: v2
    appVersion: 2.13.1
    created: "2022-09-07T08:33:17.196105+02:00"
    dependencies:
    - condition: mysql.enabled
      name: mysql
      repository: '@bitnami'
      version: ~9.1.7
    - condition: postgresql.enabled
      name: postgresql
      repository: '@bitnami'
      version: ~11.6.5
    - alias: postgresqlha
      condition: postgresqlha.enabled
      name: postgresql-ha
      repository: '@bitnami'
      version: ~9.1.5
    - condition: rabbitmq.enabled
      name: rabbitmq
      repository: '@bitnami'
      version: ~9.1.4
    - condition: redis.enabled
      name: redis
      repository: '@bitnami'
      version: ~16.12.0
    description: A Helm chart for Kubernetes to install DefectDojo
    digest: 33c21aadc2fe1c6c8d7cfba7d91a97977ab9c6e1b68b5793b654f3e2ebce34dc
    icon: https://www.defectdojo.org/img/favicon.ico
    maintainers:
    - email: defectdojo-project@owasp.org
      name: madchap
      url: https://github.com/DefectDojo/django-DefectDojo
    name: defectdojo
    urls:
    - https://github.com/SDA-SE/devops-custom-helm-charts/releases/download/0.0.10/defectdojo-1.6.37+SDA.0.0.10.tgz
    version: 1.6.37+SDA.0.0.10
generated: "2022-09-07T08:33:17.177208+02:00"
